### ISSUE TITLE
Release JSON library as nuget? 

### ISSUE THREAD

**Issue by amerkoleci** [NoelFB/Foster#10]
Hi,

Any plan to release your JSON library on nuget, i was searching for human JSON reader/writer and would probably use it.

Thanks

**Comment by NoelFB** [comment]
I'm not against separating the JSON library, however it currently relies on a few utility methods from the Foster Framework library, which would need to change.

**Comment by NoelFB** [comment]
Deciding that for now I'm going to leave this as dependent on the Foster.Framework. May revisit this in the future.
