### ISSUE TITLE
Embedded Resource 'Foster/OpenGL/Resources/batch2d.vert' doesn't exist

### ISSUE THREAD

**Issue by vatosyorgos** [NoelFB/Foster#11]
https://github.com/NoelFB/Foster/blob/b86a99c775111b79091877126b9fded56f85cb99/Platforms/OpenGL/GL_Graphics.cs#L155-L156

I cant run the "Empty Application"-Example in the Wiki. The Exception says that these two Resources do not exist, however if i change the letter "L" in OpenGL to lower case "l" it works for me. 

Is this an Issue only on my side?

**Comment by vatosyorgos** [comment]
Thank you Noel, the changes are working for me.

**Comment by NoelFB** [comment]
Awesome :)
