### ISSUE TITLE
Wrong Time.DeltaTime in the Empty Application Example

### ISSUE THREAD

**Issue by Dssdiego** [NoelFB/Foster#12]
In the **Empty Application** page of the Wiki, on _line 49_, there is the code:

`Offset += 32 * Time.DeltaTime;`

I assume the correct should be `Offset += 32 * Time.Delta`, since the **Time.cs** file on the _line 40_ has only the **_Delta_** variable

**Comment by NoelFB** [comment]
Thanks, fixed!
