### ISSUE TITLE
Only copy dependencies the OS requires

### ISSUE THREAD

**Issue by NoelFB** [NoelFB/Foster#7]
GLFW and SDL2 dependencies are all copied to the build directory, regardless of the OS (so you'll end up with .dll as well on mac, for example). csproj should handle this, however I've had problems where the behavior is different when running from Visual Studio vs. Packaging the application with `dotnet`. Need to investigate more.

**Comment by ClintKilmer** [comment]
I'm working through a similar problem right now. I've had minor success using RID conditionals in the .csproj, but it's not perfect. I'm renaming libSDL2-2.0.so.0 to libSDL2.so so my DLLImports work, since I find the new NativeLibrary stuff too verbose.

I'll report back if I find a better solution.

<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>netstandard2.1</TargetFramework>
		<<Nullable>enable</Nullable>
		<RuntimeIdentifiers>win-x64;win-x86;linux-x64;osx-x64</RuntimeIdentifiers>
	</PropertyGroup>

	<ItemGroup>
		<None Update="runtimes\linux-x64\native\libSDL2-2.0.so.0" Condition="'$(RuntimeIdentifier)'=='linux-x64'">
			<Link>libSDL2.so</Link>
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</None>
		<None Update="runtimes\linux-x64\native\libSDL2_image-2.0.so.0" Condition="'$(RuntimeIdentifier)'=='linux-x64'">
			<Link>libSDL2_image.so</Link>
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</None>
		<None Update="runtimes\linux-x64\native\libopenal.so.1" Condition="'$(RuntimeIdentifier)'=='linux-x64'">
			<Link>libsoft_oal.so</Link>
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</None>
		<None Update="runtimes\osx-x64\native\libopenal.1.dylib" Condition="'$(RuntimeIdentifier)'=='osx-x64'">
			<Link>libSDL2.dylib</Link>
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</None>
		<None Update="runtimes\osx-x64\native\libSDL2-2.0.0.dylib" Condition="'$(RuntimeIdentifier)'=='osx-x64'">
			<Link>libSDL2_image.dylib</Link>
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</None>
		<None Update="runtimes\osx-x64\native\libSDL2_image-2.0.0.dylib" Condition="'$(RuntimeIdentifier)'=='osx-x64'">
			<Link>libsoft_oal.dylib</Link>
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</None>
	</ItemGroup>

</Project>

**Comment by NoelFB** [comment]
I solved this by checking both `$(RuntimeIdentifier)`, which is set when you compile with a specific `--runtime` specified, and `[MSBuild]::IsOsPlatform` which is set based on your current OS. Kind of gross but it works!

```
  <!-- Determine OS Platform -->
  <PropertyGroup Condition="($([MSBuild]::IsOsPlatform(Windows)) and '$(RuntimeIdentifier)'=='') or '$(RuntimeIdentifier)'=='win-x64'">
    <TargetOS>win</TargetOS>
  </PropertyGroup>

  <PropertyGroup Condition="($([MSBuild]::IsOsPlatform(OSX)) and '$(RuntimeIdentifier)'=='') or '$(RuntimeIdentifier)'=='osx-x64'">
    <TargetOS>osx</TargetOS>
  </PropertyGroup>
``
