### ISSUE TITLE
Use System.Numerics.Vectors instead of own math types?

### ISSUE THREAD

**Issue by amerkoleci** [NoelFB/Foster#8]
Hi,

Maybe would be better to use .net standard numerics types from: https://www.nuget.org/packages/System.Numerics.Vectors/

It comes with SIMD optimisations as well.

**Comment by NoelFB** [comment]
Yeah this might be a good call. They're missing some functions I like but they could probably be added through extension methods.

**Comment by NoelFB** [comment]
Done.
